export const stationsData = {
  stations: [
    {
      id: "S1",
      location: "Colombo City",
      chargers: [
        
    { id: "C01", status: "Available", chargerType: "FC-SP", power: 50 },
    { id: "C02", status: "Available", chargerType: "FC-SP", power: 45 },
    { id: "C03", status: "In Use", chargerType: "FC-SP", power: 50 },
    { id: "C04", status: "Available", chargerType: "FC-SP", power: 50 },
    { id: "C05", status: "Available", chargerType: "FC-SP", power: 55 },
    { id: "C06", status: "In Use", chargerType: "FC-SP", power: 50 },
    { id: "C07", status: "Available", chargerType: "FC-SP", power: 50 },
    { id: "C08", status: "Available", chargerType: "FC-SP", power: 45 },
    { id: "C09", status: "In Use", chargerType: "FC-SP", power: 40 },
    { id: "C10", status: "Available", chargerType: "FC-SP", power: 35 },
    { id: "C11", status: "Available", chargerType: "FC-SP", power: 55 },
    { id: "C12", status: "Available", chargerType: "FC-SP", power: 40 },
    { id: "C13", status: "In Use", chargerType: "FC-SP", power: 30 },
    { id: "C14", status: "Available", chargerType: "FC-SP", power: 35 },
    { id: "C15", status: "Available", chargerType: "FC-SP", power: 75 },
    { id: "C16", status: "Available", chargerType: "FC-SP", power: 50 }, // Added
    { id: "C17", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C18", status: "In Use", chargerType: "FC-DP", power: 60 },
    { id: "C19", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C20", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C21", status: "In Use", chargerType: "FC-DP", power: 60 },
    { id: "C22", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C23", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C24", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C25", status: "In Use", chargerType: "FC-DP", power: 60 },
    { id: "C26", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C27", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C28", status: "In Use", chargerType: "FC-DP", power: 60 },
    { id: "C29", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C30", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C31", status: "Available", chargerType: "FC-DP", power: 60 }, // Added
    { id: "C32", status: "Available", chargerType: "L2-HC", power: 6.6 },
    { id: "C33", status: "In Use", chargerType: "L2-HC", power: 3.3 },
    { id: "C34", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C35", status: "In Use", chargerType: "L2-3P", power: 22 },
    { id: "C36", status: "Available", chargerType: "L2-3P", power: 11 },
    { id: "C37", status: "Available", chargerType: "L2-3P", power: 11 },
    { id: "C38", status: "Available", chargerType: "L2-3P", power: 15},
    { id: "C39", status: "In Use", chargerType: "L2-3P", power: 7 },
    { id: "C40", status: "Available", chargerType: "L2-3P", power: 22 }

 ], // Added comma here
      totalChargers: 40,
      powerRating: 75,                   // highest single fast-charger rating (kW)
      solarPV: 350,                      // larger solar array to support 40 fast chargers
      storagesolarpower: 500,            // renamed from 'battery' and increased capacity (kWh)
      maxFeederCapacity: 300,            // upgraded grid feeder to handle multiple fast chargers
      internet: "Stable",
      peakDemand: 480,                   // estimated combined demand under heavy load
      gridDraw: 300,                     // some grid draw for backup during cloudy periods
      gridOffsetPercent: 70              // majority powered by solar sources
    },
    {
      id: "S2",
      location: "Kandy",
      chargers: [
          // L2-HC (reduced to 2)
  { id: "C01", status: "Available", chargerType: "L2-HC", power: 6.6 },
  { id: "C02", status: "In Use", chargerType: "L2-HC", power: 3.3 },

  // FC-SP (high power, fast charging, urban/highway demand) - 6 chargers
  { id: "C03", status: "Available", chargerType: "FC-SP", power: 50 },
  { id: "C04", status: "In Use", chargerType: "FC-SP", power: 50 },
  { id: "C05", status: "Available", chargerType: "FC-SP", power: 55 },
  { id: "C06", status: "Available", chargerType: "FC-SP", power: 45 },
  { id: "C07", status: "Available", chargerType: "FC-SP", power: 75 },
  { id: "C08", status: "In Use", chargerType: "FC-SP", power: 50 },

  // FC-DP (dual-port fast charger) - 6 chargers
  { id: "C09", status: "In Use", chargerType: "FC-DP", power: 60 },
  { id: "C10", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C11", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C12", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C13", status: "In Use", chargerType: "FC-DP", power: 60 },
  { id: "C14", status: "Available", chargerType: "FC-DP", power: 60 },

  // L2-3P (moderate power) - 6 chargers
  { id: "C15", status: "In Use", chargerType: "L2-3P", power: 22 },
  { id: "C16", status: "Available", chargerType: "L2-3P", power: 22 },
  { id: "C17", status: "Available", chargerType: "L2-3P", power: 11 },
  { id: "C18", status: "Available", chargerType: "L2-3P", power: 11 },
  { id: "C19", status: "Available", chargerType: "L2-3P", power: 7 },
  { id: "C20", status: "In Use", chargerType: "L2-3P", power: 7 }
      ],
      totalChargers: 20,
      powerRating: 6.6,                // typical L2 charger power
      solarPV: 180,                   // medium solar array for smaller station
      storagesolarpower: 200,          // renamed from 'battery'
      maxFeederCapacity: 150,          // smaller feeder capacity than Colombo
      internet: "Stable",
      peakDemand: 132,                 // 6.6 kW × 20 chargers
      gridDraw: 150,                    // grid used minimally for backup
      gridOffsetPercent: 62            // majorit6y powered by solar & storage
    },
    {

  id: "S3",
  location: "Galle",
  chargers:[
  // FC-SP (16 chargers)
  { id: "C01", status: "Available", chargerType: "FC-SP", power: 50 },
  { id: "C02", status: "Available", chargerType: "FC-SP", power: 45 },
  { id: "C03", status: "In Use", chargerType: "FC-SP", power: 50 },
  { id: "C04", status: "Available", chargerType: "FC-SP", power: 50 },
  { id: "C05", status: "Available", chargerType: "FC-SP", power: 55 },
  { id: "C06", status: "In Use", chargerType: "FC-SP", power: 50 },
  { id: "C07", status: "Available", chargerType: "FC-SP", power: 50 },
  { id: "C08", status: "Available", chargerType: "FC-SP", power: 45 },
  { id: "C09", status: "In Use", chargerType: "FC-SP", power: 40 },
  { id: "C10", status: "Available", chargerType: "FC-SP", power: 35 },
  { id: "C11", status: "Available", chargerType: "FC-SP", power: 55 },
  { id: "C12", status: "Available", chargerType: "FC-SP", power: 40 },
  { id: "C13", status: "In Use", chargerType: "FC-SP", power: 30 },
  { id: "C14", status: "Available", chargerType: "FC-SP", power: 35 },
  { id: "C15", status: "Available", chargerType: "FC-SP", power: 75 },
  { id: "C16", status: "Available", chargerType: "FC-SP", power: 50 },

  // FC-DP (15 chargers)
  { id: "C17", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C18", status: "In Use", chargerType: "FC-DP", power: 60 },
  { id: "C19", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C20", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C21", status: "In Use", chargerType: "FC-DP", power: 60 },
  { id: "C22", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C23", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C24", status: "In Use", chargerType: "FC-DP", power: 60 },
  { id: "C25", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C26", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C27", status: "In Use", chargerType: "FC-DP", power: 60 },
  { id: "C28", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C29", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C30", status: "Available", chargerType: "FC-DP", power: 60 },
  { id: "C31", status: "Available", chargerType: "FC-DP", power: 60 },

  // L2-HC (reduced to 2 chargers)
  { id: "C32", status: "Available", chargerType: "L2-HC", power: 6.6 },
  { id: "C33", status: "In Use", chargerType: "L2-HC", power: 3.3 },

  // L2-3P (increased to 7 chargers)
  { id: "C34", status: "Available", chargerType: "L2-3P", power: 22 },
  { id: "C35", status: "In Use", chargerType: "L2-3P", power: 22 },
  { id: "C36", status: "Available", chargerType: "L2-3P", power: 11 },
  { id: "C37", status: "Available", chargerType: "L2-3P", power: 11 },
  { id: "C38", status: "Available", chargerType: "L2-3P", power: 7 },
  { id: "C39", status: "In Use", chargerType: "L2-3P", power: 7 },
  { id: "C40", status: "Available", chargerType: "L2-3P", power: 22 }
      ],
  totalChargers: 40,
  powerRating: 75,                  // highest single charger rating
  solarPV: 300,                   // large solar setup
  storagesolarpower: 400,           // renamed and increased capacity
  maxFeederCapacity: 200,           // upgraded grid feeder
  internet: "Stable",
  peakDemand: 480,                  // full fast-charger load
  gridDraw: 200,                    // grid as backup
  gridOffsetPercent: 65             // mostly solar + storage powered

    },
    {
      id: "S4",
  location: "Negombo",
  chargers: [
 // FC-SP (10 chargers)
    { id: "C01", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C02", status: "Available", chargerType: "FC-SP", power: 45 },
    { id: "C03", status: "In Use", chargerType: "FC-SP", power: 50 },
    { id: "C04", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C05", status: "Available", chargerType: "FC-SP", power: 55 },
    { id: "C06", status: "In Use", chargerType: "FC-SP", power: 50 },
    { id: "C07", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C08", status: "Available",chargerType: "FC-SP", power: 45 },
    { id: "C09", status: "In Use", chargerType: "FC-SP", power: 40 },
    { id: "C10", status: "Available",chargerType: "FC-SP", power: 35 },

    // FC-DP (10 chargers)
    { id: "C11", status: "In Use",chargerType: "FC-DP", power: 60 },
    { id: "C12", status: "Available",chargerType: "FC-DP", power: 60 },
    { id: "C13", status: "In Use", chargerType: "FC-DP", power: 60 },
    { id: "C14", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C15", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C16", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C17", status: "Available",chargerType: "FC-DP", power: 60 },
    { id: "C18", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C19", status: "Available", chargerType: "FC-DP", power: 60 },
    { id: "C20", status: "Available", chargerType: "FC-DP", power: 60 },

    // L2-HC (2 chargers)
    { id: "C21", status: "In Use", chargerType: "L2-HC", power: 6.6 },
    { id: "C22", status: "Available",chargerType: "L2-HC", power: 3.3 },

    // L2-3P (8 chargers)
    { id: "C23", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C24", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C25", status: "Available", chargerType: "L2-3P", power: 11 },
    { id: "C26", status: "In Use",chargerType: "L2-3P", power: 11 },
    { id: "C27", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C28", status: "In Use",chargerType: "L2-3P", power: 22 },
    { id: "C29", status: "Available",chargerType: "L2-3P", power: 11 },
    { id: "C30", status: "Available",chargerType: "L2-3P", power: 11 }
  ],
  totalChargers: 30,
  powerRating: 75,
  solarPV: 200,
  storagesolarpower: 300,
  maxFeederCapacity: 150,
  internet: "Stable",
  peakDemand: 600,
  gridDraw:150,
  gridOffsetPercent: 65,
},

{
  id: "S5",
  location: "Ratnapura",
  chargers: [
    { id: "C01", status: "Available",  chargerType: "FC-SP", power: 50 },

    // FC-DP (1 charger)
    { id: "C02", status: "In Use",  chargerType: "FC-DP", power: 60 },

    // L2-3P (6 chargers)
    { id: "C03", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C04", status: "Available",  chargerType: "L2-3P", power: 22 },
    { id: "C05", status: "In Use",  chargerType: "L2-3P", power: 10 },
    { id: "C06", status: "Available", chargerType: "L2-3P", power: 15 },
    { id: "C07", status: "Available", chargerType: "L2-3P", power: 20 },
    { id: "C08", status: "Available", chargerType: "L2-HC", power: 6.6 },
  ],
  totalChargers: 8,
  powerRating: 22,
  solarPV: 200,
  storagesolarpower: 150,
  maxFeederCapacity: 112,
  internet: "Stable",
  peakDemand: 176,
  gridDraw: 112,
  gridOffsetPercent: 36,
},

{
  id: "S6",
  location: "Kurunegala",
  chargers: [
    { id: "C01", status: "Available",  chargerType: "FC-SP", power: 50 },
    { id: "C02", status: "In Use", chargerType: "FC-DP", power: 75 },
    { id: "C03", status: "Available", chargerType: "FC-SP", power: 50 },
    { id: "C04", status: "Available", chargerType: "FC-DP", power: 75 },
    { id: "C05", status: "Available", chargerType: "FC-SP", power: 50 },
    { id: "C06", status: "In Use",  chargerType: "FC-DP", power: 75 },
    { id: "C07", status: "Available",  chargerType: "FC-SP", power: 50 },
    { id: "C08", status: "Available", chargerType: "FC-DP", power: 75 },
    { id: "C09", status: "Available", chargerType: "FC-SP", power: 50 },
    { id: "C10", status: "Available", chargerType: "FC-DP", power: 75 },
    { id: "C11", status: "Available",  chargerType: "FC-SP", power: 50 },
    { id: "C12", status: "In Use", chargerType: "FC-DP", power: 75 },
  ],
  totalChargers: 12,
  powerRating: 75,
  solarPV: 200,
  storagesolarpower: 250,
  maxFeederCapacity:150,
  internet: "Stable",
  peakDemand: 600,
  gridDraw:150,
  gridOffsetPercent: 60,
},

{
  id: "S7",
  location: "Anuradhapura",
  chargers: [
    { id: "C01", status: "Available",  chargerType: "L2-3P", power: 22 },
    { id: "C02", status: "In Use",  chargerType: "L2-3P", power: 22 },
    { id: "C03", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C04", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C05", status: "Available", chargerType : "L2-3P", power: 22 },
    { id: "C06", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C07", status: "In Use", chargerType: "L2-3P", power: 22 },
    { id: "C08", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C09", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C10", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C11", status: "In Use",chargerType: "L2-3P", power: 22 },
    { id: "C12", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C13", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C14", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C15", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C16", status: "In Use", chargerType: "L2-3P", power: 22 },
    { id: "C17", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C18", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C19", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C20", status: "In Use", chargerType: "L2-3P", power: 22 },
  ],
  totalChargers: 20,
  powerRating: 22,
  solarPV:200,
  storagesolarpower: 200,
  maxFeederCapacity: 100,
  internet: "Stable",
  peakDemand: 220,
  gridDraw: 100,
  gridOffsetPercent: 55,
},

{
  id: "S8",
  location: "Jaffna",
  chargers: [
    { id: "C01", status: "In Use", chargerType: "FC-SP", power: 50 },
    { id: "C02", status: "Available",chargerType: "FC-DP", power: 75 },
    { id: "C03", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C04", status: "In Use", chargerType: "FC-DP", power: 75 },
    { id: "C05", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C06", status: "Available",chargerType: "FC-DP", power: 75 },
    { id: "C07", status: "In Use", chargerType: "FC-SP", power: 50 },
    { id: "C08", status: "Available",chargerType: "FC-DP", power: 75 },
    { id: "C09", status: "Available", chargerType: "FC-SP", power: 50 },
    { id: "C10", status: "Available",chargerType: "FC-DP", power: 75 },
    { id: "C11", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C12", status: "Available", chargerType: "FC-DP", power: 75 },
    { id: "C13", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C14", status: "In Use", chargerType: "FC-DP", power: 75 },
    { id: "C15", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C16", status: "Available",chargerType: "FC-DP", power: 75 },
    { id: "C17", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C18", status: "Available",chargerType: "FC-DP", power: 75 },
    { id: "C19", status: "Available",chargerType: "FC-SP", power: 50 },
    { id: "C20", status: "In Use", chargerType: "FC-DP", power: 75 },
  ],
  totalChargers: 20,
  powerRating: 75,
  solarPV: 300,
  storagesolarpower: 500,
  maxFeederCapacity: 250,
  internet: "Stable",
  peakDemand: 800,
  gridDraw: 250,
  gridOffsetPercent: 65,
},

{
  id: "S9",
  location: "Matara",
  chargers: [
    { id: "C01", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C02", status: "In Use",  chargerType: "L2-3P", power: 22 },
    { id: "C03", status: "Available",  chargerType: "FC-SP", power: 50 },
    { id: "C04", status: "Available",  chargerType: "L2-3P", power: 22 },
    { id: "C05", status: "Available", chargerType: "FC-DP", power: 75 },
    { id: "C06", status: "Available", chargerType: "L2-3P", power: 22 },
    { id: "C07", status: "In Use", chargerType: "L2-3P", power: 22 },
    { id: "C08", status: "Available",  chargerType: "FC-SP", power: 50 },
    { id: "C09", status: "Available",  chargerType: "L2-3P", power: 22 },
    { id: "C10", status: "Available",  chargerType: "FC-DP", power: 75 },
    { id: "C11", status: "Available",  chargerType: "L2-3P", power: 22 },
    { id: "C12", status: "In Use",  chargerType: "FC-SP", power: 50 },
    { id: "C13", status: "Available",  chargerType: "L2-3P", power: 22 },
    { id: "C14", status: "Available",  chargerType: "FC-DP", power: 75 },
    { id: "C15", status: "Available",  chargerType: "L2-3P", power: 22 },
    { id: "C16", status: "Available", chargerType: "FC-SP", power: 50 },
    { id: "C17", status: "In Use",  chargerType: "L2-3P", power: 22 },
    { id: "C18", status: "Available",  chargerType: "FC-DP", power: 75 },
    { id: "C19", status: "Available",  chargerType: "L2-3P", power: 22 },
    { id: "C20", status: "Available",  chargerType: "L2-3P", power: 22 },
  ],
  totalChargers: 30,
  powerRating: 50,
  solarPV: 300,
  storagesolarpower: 350,
  maxFeederCapacity: 200,
  internet: "Stable",
  peakDemand: 480,
  gridDraw: 200,
  gridOffsetPercent: 60,
},

{
  id: "S10",
  location: "Badulla",
  chargers: [
    { id: "C01", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C02", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C03", status: "In Use",chargerType: "L2-3P", power: 22 },
    { id: "C04", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C05", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C06", status: "In Use", chargerType: "L2-3P", power: 22 },
    { id: "C07", status: "Available",chargerType: "L2-3P", power: 22 },
    { id: "C08", status: "Available",chargerType: "L2-3P", power: 22 },
  ],
  totalChargers: 8,
  powerRating: 22,
  solarPV: 80,
  storagesolarpower: 120,
  maxFeederCapacity: 150,
  internet: "Stable",
  peakDemand: 176,
  gridDraw: 150,
  gridOffsetPercent: 50,
    },
  ],
}

export const vehiclesData = {
  vehicles: [
    {
      id: "EV001",
      make: "Tesla",
      model: "Model 3",
      year: "2023",
      owner: "John Silva",
      email: "john@email.com",
      phone: "+94771234567",
      status: "Active",
      registered: "2024-01-15",
      lastCharge: "2024-01-20",
      totalSessions: 45,
      rfidCard: "RF001234",
      licensePlate: "CAR-1234",
    },
    {
      id: "EV002",
      make: "Nissan",
      model: "Leaf",
      year: "2022",
      owner: "Maria Fernando",
      email: "maria@email.com",
      phone: "+94771234568",
      status: "Active",
      registered: "2024-01-14",
      lastCharge: "2024-01-19",
      totalSessions: 32,
      rfidCard: "RF001235",
      licensePlate: "CAR-1235",
    },
    {
      id: "EV003",
      make: "BMW",
      model: "i3",
      year: "2023",
      owner: "Rajesh Kumar",
      email: "rajesh@email.com",
      phone: "+94771234569",
      status: "Suspended",
      registered: "2024-01-13",
      lastCharge: "2024-01-18",
      totalSessions: 28,
      rfidCard: "RF001236",
      licensePlate: "CAR-1236",
    },
  ],
}

export const users = [
  {
    id: "USR001",
    name: "John Silva",
    email: "john.silva@ems.lk",
    phone: "+94771234567",
    role: "Super Admin",
    status: "Active",
    vehicles: 1,
    paymentMethods: ["Visa *1234", "PayPal"],
    totalSpent: "LKR 45,670",
    joinDate: "2023-12-01",
    lastActivity: "2024-01-20",
    chargingSessions: 45,
    preferredStations: ["Colombo", "Kandy"],
    permissions: ["Full System Access", "User Management", "System Configuration", "Security Settings"],
    createdDate: "2023-12-01",
    loginCount: 245,
  },
  {
    id: "USR002",
    name: "Maria Fernando",
    email: "maria.fernando@ems.lk",
    phone: "+94771234568",
    role: "Station Manager",
    status: "Active",
    vehicles: 2,
    paymentMethods: ["MasterCard *5678"],
    totalSpent: "LKR 32,450",
    joinDate: "2023-11-15",
    lastActivity: "2024-01-19",
    chargingSessions: 32,
    preferredStations: ["Galle", "Matara"],
    permissions: ["Station Management", "Charger Control", "Local Reports", "Maintenance Scheduling"],
    createdDate: "2023-11-15",
    loginCount: 189,
  },
  {
    id: "USR003",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@ems.lk",
    phone: "+94771234569",
    role: "Finance",
    status: "Inactive",
    vehicles: 1,
    paymentMethods: ["Visa *9012"],
    totalSpent: "LKR 28,900",
    joinDate: "2023-10-20",
    lastActivity: "2024-01-18",
    chargingSessions: 28,
    preferredStations: ["Colombo", "Negombo"],
    permissions: ["Billing Management", "Revenue Reports", "Payment Processing", "Financial Analytics"],
    createdDate: "2023-10-20",
    loginCount: 156,
  },
  {
    id: "USR004",
    name: "Priya Wickramasinghe",
    email: "priya.w@ems.lk",
    phone: "+94771234570",
    role: "Maintenance",
    status: "Active",
    vehicles: 0,
    paymentMethods: [],
    totalSpent: "LKR 0",
    joinDate: "2024-01-05",
    lastActivity: "2024-01-20",
    chargingSessions: 0,
    preferredStations: [],
    permissions: ["Equipment Access", "Maintenance Logs", "Fault Reporting", "Technical Reports"],
    createdDate: "2024-01-05",
    loginCount: 67,
  },
]

export const fleets = [
  {
    id: "FLT001",
    company: "Colombo Taxi Services",
    contact: "Manager Silva",
    email: "fleet@colombotaxi.lk",
    vehicles: 25,
    activeVehicles: 23,
    monthlySpend: "LKR 125,000",
    discount: "15%",
    status: "Active",
    contract: "Annual",
    createdDate: "2023-08-15",
    billingAddress: "123 Main Street, Colombo 03",
    taxId: "TAX001234567",
  },
  {
    id: "FLT002",
    company: "Green Delivery Ltd",
    contact: "Operations Team",
    email: "ops@greendelivery.lk",
    vehicles: 12,
    activeVehicles: 11,
    monthlySpend: "LKR 67,500",
    discount: "10%",
    status: "Active",
    contract: "Monthly",
    createdDate: "2023-11-20",
    billingAddress: "456 Business Park, Kandy",
    taxId: "TAX001234568",
  },
  {
    id: "FLT003",
    company: "Express Logistics",
    contact: "Fleet Manager",
    email: "fleet@expresslogistics.lk",
    vehicles: 8,
    activeVehicles: 7,
    monthlySpend: "LKR 45,000",
    discount: "8%",
    status: "Active",
    contract: "Quarterly",
    createdDate: "2023-12-10",
    billingAddress: "789 Industrial Zone, Galle",
    taxId: "TAX001234569",
  },
]

export interface Booking {
  id: string
  userId: string
  userName: string
  vehicleId: string
  vehiclePlate: string
  stationId: string
  stationLocation: string
  chargerId: string
  bookingDate: string
  startTime: string
  endTime: string
  duration: number // in minutes
  status: "Scheduled" | "Active" | "Completed" | "Cancelled" | "No Show"
  bookingSource: "Mobile App" | "Website" | "Admin Panel" | "RFID"
  powerRequested: number // in kW
  estimatedCost: string
  actualCost?: string
  paymentMethod: string
  paymentStatus: "Pending" | "Paid" | "Failed" | "Refunded"
  createdAt: string
  updatedAt: string
  notes?: string
}

export const bookings: Booking[] = [
  {
    id: "BK001",
    userId: "USR001",
    userName: "John Silva",
    vehicleId: "EV001",
    vehiclePlate: "CAR-1234",
    stationId: "S1",
    stationLocation: "Colombo City",
    chargerId: "C01",
    bookingDate: "2024-01-21",
    startTime: "09:00",
    endTime: "11:00",
    duration: 120,
    status: "Completed",
    bookingSource: "Mobile App",
    powerRequested: 50,
    estimatedCost: "LKR 1,200",
    actualCost: "LKR 1,150",
    paymentMethod: "Visa *1234",
    paymentStatus: "Paid",
    createdAt: "2024-01-20T15:30:00Z",
    updatedAt: "2024-01-21T11:05:00Z",
    notes: "Fast charging session completed successfully",
  },
  {
    id: "BK002",
    userId: "USR002",
    userName: "Maria Fernando",
    vehicleId: "EV002",
    vehiclePlate: "CAR-1235",
    stationId: "S3",
    stationLocation: "Galle",
    chargerId: "C02",
    bookingDate: "2024-01-21",
    startTime: "14:00",
    endTime: "16:30",
    duration: 150,
    status: "Active",
    bookingSource: "Website",
    powerRequested: 22,
    estimatedCost: "LKR 900",
    paymentMethod: "MasterCard *5678",
    paymentStatus: "Paid",
    createdAt: "2024-01-21T08:15:00Z",
    updatedAt: "2024-01-21T14:00:00Z",
    notes: "Regular charging session in progress",
  },
  {
    id: "BK003",
    userId: "USR003",
    userName: "Rajesh Kumar",
    vehicleId: "EV003",
    vehiclePlate: "CAR-1236",
    stationId: "S1",
    stationLocation: "Colombo City",
    chargerId: "C03",
    bookingDate: "2024-01-22",
    startTime: "10:00",
    endTime: "12:00",
    duration: 120,
    status: "Scheduled",
    bookingSource: "Mobile App",
    powerRequested: 50,
    estimatedCost: "LKR 1,200",
    paymentMethod: "Visa *9012",
    paymentStatus: "Pending",
    createdAt: "2024-01-21T16:45:00Z",
    updatedAt: "2024-01-21T16:45:00Z",
    notes: "Advance booking for tomorrow morning",
  },
  {
    id: "BK004",
    userId: "USR001",
    userName: "John Silva",
    vehicleId: "EV001",
    vehiclePlate: "CAR-1234",
    stationId: "S2",
    stationLocation: "Kandy",
    chargerId: "C01",
    bookingDate: "2024-01-20",
    startTime: "16:00",
    endTime: "17:30",
    duration: 90,
    status: "Cancelled",
    bookingSource: "Website",
    powerRequested: 50,
    estimatedCost: "LKR 900",
    paymentMethod: "Visa *1234",
    paymentStatus: "Refunded",
    createdAt: "2024-01-19T12:30:00Z",
    updatedAt: "2024-01-20T14:00:00Z",
    notes: "Cancelled due to vehicle breakdown",
  },
  {
    id: "BK005",
    userId: "USR002",
    userName: "Maria Fernando",
    vehicleId: "EV002",
    vehiclePlate: "CAR-1235",
    stationId: "S9",
    stationLocation: "Matara",
    chargerId: "C01",
    bookingDate: "2024-01-19",
    startTime: "11:00",
    endTime: "13:00",
    duration: 120,
    status: "No Show",
    bookingSource: "RFID",
    powerRequested: 22,
    estimatedCost: "LKR 600",
    paymentMethod: "MasterCard *5678",
    paymentStatus: "Failed",
    createdAt: "2024-01-19T09:15:00Z",
    updatedAt: "2024-01-19T13:30:00Z",
    notes: "Customer did not show up for scheduled session",
  },
]

export const vehicleCategories = [
  { id: "electricCar", name: "Electric Car", batteryCapacity: 60, maxChargingPower: 150 },
  { id: "electricVan", name: "Electric Van", batteryCapacity: 80, maxChargingPower: 100 },
  { id: "electricBus", name: "Electric Bus", batteryCapacity: 300, maxChargingPower: 250 },
  { id: "electricTuk", name: "Electric Tuk-Tuk", batteryCapacity: 15, maxChargingPower: 7 },
  { id: "electricBike", name: "Electric Bike", batteryCapacity: 3, maxChargingPower: 3 },
]
